stages:
  - build

variables:
  BASE_IMAGE_NAME: "vpn-bot"
  TAG: "latest"
  REGISTRY: "registry.vladislav-novikov.ru"
  SERVICE_NAME: "bot-service"

default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY

build_single_service:
  stage: build
  tags:
    - build
  script:
    - IMAGE_NAME="${BASE_IMAGE_NAME}-${SERVICE_NAME}"
    - echo "Building image for service $SERVICE_NAME with tag: $TAG ..."
    - docker build \
      --build-arg SERVICE_NAME="$SERVICE_NAME" \
      -t "$REGISTRY/$IMAGE_NAME:$TAG" \
      -f ./Dockerfile-$SERVICE_NAME \
      .
    - echo "Pushing image $REGISTRY/$IMAGE_NAME:$TAG ..."
    - docker push "$REGISTRY/$IMAGE_NAME:$TAG"
  only:
    - main
