stages:
  - build
  - push

variables:
  IMAGE_NAME: "bot-service"
  IMAGE_TAG: "latest"
  REGISTRY_URL: "registry.vladislav-novikov.ru"
  IMAGE_FULL_PATH: "$REGISTRY_URL/$CI_PROJECT_PATH/$IMAGE_NAME:$IMAGE_TAG"

build:
  image: docker:24.0.5
  stage: build
  tags:
    - build
  services:
    - docker:24.0.5-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u $CI_REGISTRY_USER --password-stdin
    - docker build -f ./Dockerfile-bot-service -t $IMAGE_FULL_PATH .
    - docker push $IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH