stages:
  - build
  - push

variables:
  IMAGE_NAME: "bot-service"
  IMAGE_TAG: "latest"
  # Указываем полный путь до вашего реестра
  REGISTRY_URL: "registry.vladislav-novikov.ru"
  # Полный путь до образа в вашем реестре
  IMAGE_FULL_PATH: "$REGISTRY_URL/$CI_PROJECT_PATH/$IMAGE_NAME:$IMAGE_TAG"

build-image:
  stage: build
  image: docker:24.0
  tags:
    - build
  services:
    - docker:24.0-dind
  before_script:
    # Безопасный логин через stdin
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin "$REGISTRY_URL"
  script:
    - docker build -f Dockerfile-bot-service -t $IMAGE_FULL_PATH .
    - docker push $IMAGE_FULL_PATH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH