stages:
  - build

variables:
  BASE_IMAGE_NAME: "vpn-bot"
  TAG: "latest"
  REGISTRY: "registry.vladislav-novikov.ru"
  SERVICE_NAME: "bot-service"

default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY

build_single_service:
  stage: build
  tags:
    - build
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
  script:
    - IMAGE_NAME="${BASE_IMAGE_NAME}-${SERVICE_NAME}"
    - docker buildx build \
      --build-arg SERVICE_NAME="$SERVICE_NAME" \
      -t "$REGISTRY/$IMAGE_NAME:$TAG" \
      -f ./Dockerfile-$SERVICE_NAME \
      --push .  # Added --push to push directly
  only:
    - main