image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE         # Например: registry.vladislav-novikov.ru/nvs/monorepo
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""                # Отключает TLS внутри dind

stages:
  - build
  - push

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

# Шаблон для сборки сервисов
.build_template: &build_template
  stage: build
  tags:
    - build
  only:
    - main
    - master
  script:
    - docker info
    - docker build --build-arg SERVICE_NAME=$SERVICE_NAME -t "$IMAGE_NAME:$SERVICE_NAME-$IMAGE_TAG" -f $DOCKERFILE .
    - docker push "$IMAGE_NAME:$SERVICE_NAME-$IMAGE_TAG"
    - docker tag "$IMAGE_NAME:$SERVICE_NAME-$IMAGE_TAG" "$IMAGE_NAME:$SERVICE_NAME-latest"
    - docker push "$IMAGE_NAME:$SERVICE_NAME-latest"

# Каждая job использует шаблон и подставляет имя сервиса и Dockerfile
build-bot-service:
  <<: *build_template
  variables:
    SERVICE_NAME: bot-service
    DOCKERFILE: Dockerfile-bot-service

build-user-service:
  <<: *build_template
  variables:
    SERVICE_NAME: user-service
    DOCKERFILE: Dockerfile-user-service

build-payment-service:
  <<: *build_template
  variables:
    SERVICE_NAME: payment-service
    DOCKERFILE: Dockerfile-payment-service

build-vpn-service:
  <<: *build_template
  variables:
    SERVICE_NAME: vpn-service
    DOCKERFILE: Dockerfile-vpn-service
