image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  BOT_SERVICE_NAME: bot-service
  PAYMENT_SERVICE_NAME: payment-service
  USER_SERVICE_NAME: user-service
  VPN_SERVICE_NAME: vpn-service
  DOCKER_TLS_CERTDIR: ""  # Отключает TLS, упрощает соединение с dind

stages:
  - build
  - push

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build-bot-service:
  stage: build
  tags:
    - build
  script:
    - docker info  # отладка
    - docker build --build-arg SERVICE_NAME=$BOT_SERVICE_NAME -t "$IMAGE_NAME:$IMAGE_TAG" -f Dockerfile-bot-service .
    - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
    - master
build-payment-service:
  stage: build
  tags:
    - build
  script:
    - docker info  # отладка
    - docker build --build-arg SERVICE_NAME=$PAYMENT_SERVICE_NAME -t "$IMAGE_NAME:$IMAGE_TAG" -f Dockerfile-payment-service .
    - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
    - master
build-user-service:
  stage: build
  tags:
    - build
  script:
    - docker info  # отладка
    - docker build --build-arg SERVICE_NAME=$USER_SERVICE_NAME -t "$IMAGE_NAME:$IMAGE_TAG" -f Dockerfile-user-service .
    - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
    - master
build-vpn-service:
  stage: build
  tags:
    - build
  script:
    - docker info  # отладка
    - docker build --build-arg SERVICE_NAME=$VPN_SERVICE_NAME -t "$IMAGE_NAME:$IMAGE_TAG" -f Dockerfile-vpn-service .
    - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
    - master
