image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  SERVICE_NAME: bot-service
  DOCKER_TLS_CERTDIR: ""  # Отключает TLS, упрощает соединение с dind

stages:
  - build
  - push

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build:
  stage: build
  tags:
    - build
  script:
    - docker info  # отладка
    - docker build --build-arg SERVICE_NAME=$SERVICE_NAME -t "$IMAGE_NAME:$IMAGE_TAG" -f Dockerfile-bot-service .
    - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
    - master
