services:
  db:
    image: postgres
    container_name: db
    restart: always
    shm_size: 128mb
    volumes:
      - .docker/db_data/:/var/lib/postgresql/data/
      - .docker/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: highjin
      POSTGRES_PASSWORD: 12345678B
    ports:
      - "5430:5432"

volumes:
  pgdata:
    driver: local