services:
  db:
    image: postgres
    container_name: db
    restart: always
    shm_size: 128mb
    volumes:
      - .docker/db_data/:/var/lib/postgresql/data/
      - .docker/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: highjin
      POSTGRES_PASSWORD: 12345678B
    ports:
      - "5430:5432"
    networks:
      - local

  bot_service:
    container_name: bot_service
    build:
      dockerfile: ./Dockerfile-bot-dev
      args:
        - SERVICE_NAME=bot-service
    environment:
      - GO111MODULE=on
    volumes:
      - ./services/bot-service:/app/bot-service
      - ./services/pkg:/app/pkg
    networks:
      - local

  payment_service:
    container_name: payment_service
    build:
      dockerfile: ./Dockerfile-bot-dev
      args:
        - SERVICE_NAME=payment-service
    environment:
      - GO111MODULE=on
    volumes:
      - ./services/payment-service:/app/payment-service
      - ./services/pkg:/app/pkg
    networks:
      - local
    ports:
      - "228:8080"
      - "2345:2345"

  user_service:
    container_name: user_service
    build:
      dockerfile: ./Dockerfile-bot-dev
      args:
        - SERVICE_NAME=user-service
    environment:
      - GO111MODULE=on
    volumes:
      - ./services/user-service:/app/user-service
      - ./services/pkg:/app/pkg
    ports:
      - "322:22822"
    networks:
      - local

  vpn_service:
    container_name: vpn_service
    build:
      dockerfile: ./Dockerfile-bot-dev
      args:
        - SERVICE_NAME=vpn-service
    environment:
      - GO111MODULE=on
    volumes:
      - ./services/vpn-service:/app/vpn-service
      - ./services/pkg:/app/pkg
    ports:
      - "433:3344"
    networks:
      - local

  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: [ "-js" ]  # Включаем JetStream (короткая опция)
    networks:
      - local

  nats_ui:
    container_name: nats_ui
    image: ghcr.io/nats-nui/nui:latest
    volumes:
      - ./.docker/nui/db:/db
      - ./.docker/nui/creds:/nats-creds:ro
    ports:
      - "31311:31311"
    networks:
      - local

networks:
  local:
volumes:
  pgdata:
    driver: local