logger:
  path: "./logs"
  name: "vpn-bot"
  is_output: true

base:
  app_port:
  swagger:

database:
  path: database/user_service.db
  host:
  user:
  password:
  db:
  port:

nats_publisher:
  url: