logger:
  path: "./logs"
  name: "vpn-bot"
  is_output: true

base:
  app_port: 22822
  swagger: true

database:
  path: database/user_service.db
  host: localhost
  user: highjin
  password: 12345678B
  db: user_data
  port: 5430