logger:
  path: "./logs"
  name: "payment-service"
  is_output: false

vpn_service:
  base_url:
  username:
  password:
  inbound_id:

user_service:
  url: http://localhost:22822/api

bot_settings:
  token:

