logger:
  path: "./logs"
  name: "payment-service"
  is_output: false

vpn_service:
  base_url:
  username:
  password:
  inbound_id:

user_service:
  url:

base:
  app_port: 8080

bot_settings:
  token:

