logger:
  path: "./logs"
  name: "vpn-bot"
  is_output: false

database:
  host:
  user:
  password:
  db:
  port:

user_service:
  url:

vpn_service:
  url:

payment_service:
  url:

bot_settings:
  token:

base:
  app_port:

nats_publisher:
  url:

