root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  cmd = "go build -o ./tmp/main ./src/cmd/main.go"  # Собираем бинарник
  bin = "./tmp/main"  # Запускаем собранный бинарник
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "src/webapp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["src"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 500  # Проверять изменения каждые 500 мс
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 2000
  send_interrupt = false
  stop_on_error = false

[color]
  app = "orange"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
