name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Lint bot-service
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: services/
          args: bot-service/src/...

      - name: Lint user-service
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: services/
          args: user-service/src/...
