name: golangci-lint and Docker Build
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          SERVICES=("bot-service" "user-service" "payment-service" "vpn-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Building $SERVICE"
            docker build -f "Dockerfile-$SERVICE" -t "your-registry/$SERVICE:latest" .
            docker push "your-registry/$SERVICE:latest"
          done
