name: golangci-lint and Docker Build
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Lint bot-service
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: services/
          args: bot-service/src/...

      - name: Lint user-service
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: services/
          args: user-service/src/...

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: golangci  # Указывает, что этот job должен ждать завершения golangci
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          SERVICES=("bot-service" "user-service" "payment-service" "vpn-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Building $SERVICE"
            docker build -f "Dockerfile-$SERVICE" -t "your-registry/$SERVICE:latest" .
            docker push "your-registry/$SERVICE:latest"
          done
